Output Added
AzXeus/XComModBridge pull request #1
Opened 2024-08-02 03:40 UTC by Dustin1230

Added a commented section for the hook files that shows the output of the PseudoCode changes.

2024-08-02 12:12 UTC, AzXeus requested changes

2024-08-02 12:12 UTC, AzXeus commented on Puesdo Hooks/XComGame/XGAbility/ApplyCost.txt
output comment doesn't match psuedocode

2024-08-02 12:12 UTC, AzXeus commented on Puesdo Hooks/XComGame/XGAbility/ShowAbility.txt
output comment doesn't match psuedocode

2024-08-02 12:12 UTC, AzXeus commented on Puesdo Hooks/XComGame/XGUnit/AbsorbDamage.txt
output comment doesn't match psuedocode

2024-08-02 12:12 UTC, AzXeus commented on Puesdo Hooks/XComGame/XGUnit/ApplyInventoryStatModifiers.txt
output comment doesn't match psuedocode

2024-08-02 12:12 UTC, AzXeus commented on Puesdo Hooks/XComGame/XGUnit/OnTurnBeginHook.txt
output comment doesn't match psuedocode

2024-08-03 20:09 UTC, Dustin1230 commented
Made the changes for ya

2024-08-03 20:10 UTC, AzXeus approved these changes
all looks good

2024-08-03 20:16 UTC, merged